### ISSUE TITLE
Publish `redmine_gtt_export` plugin:

### ISSUE THREAD

**Issue by dkastl** [gtt-project/redmine_gtt_export#1]
- [x] use branch `main`
- [x] has branch `develop`
- [x] has tests (if not create issue)
- [ ] has CI with GH Actions (if not create issue)
- [x] has `LICENSE`
- [x] has `README.md`
- [x] comments are in English (if not create issue)

**Comment by sanak** [comment]
About CI with GH Actions, I will create a new issue for that.
Publish is already done, so I close this.
